### ISSUE TITLE
This lesson is largely duplicative of git-remotes-with-github-readme-v-000

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/git-remote-code-along#11]
With a few exceptions (such as the explanation of the `-u` flag, which I just submitted a pull request to improve), the lesson's text is almost entirely lifted from [the previous lesson in the Git and GitHub sequence](https://github.com/learn-co-students/git-remotes-with-github-readme-v-000).

**Comment by pletcher** [comment]
Hm, that's a good catch. What track are you working on?

**Comment by gj** [comment]
Full Stack Web Development

**Comment by pletcher** [comment]
Removed it from most batches.
