### ISSUE TITLE
Suggestion on this code along 

### ISSUE THREAD

**Issue by lqf2b8** [learn-co-curriculum/git-remote-code-along#14]
I feel like there is a bit of ambiguity in this code along. 

It goes straight from "git remote add origin your-remote-repository-URL" to  "Let's add some new content to our README.md file" then to "Now look at the remote repo on GitHub. Notice the new text in the README is not there"

If you code along just like the lab says there isn't any README.md file in the repo at all because there was never a initializing push done to push the local copy to the github repo. Not a big deal if you payed attention in the prior lesson but I feel like the "git push -u origin master" step should be added. Then a step showing that the initial README.md file is viewable on github. Then go into the steps about changing the local copy of README.md and how it isn't changed on the remote copy.

Hope that makes sense.

If not let me know.

**Comment by gj** [comment]
Hi @lqf2b8 !

The steps to [`Create a new directory and add a file`](https://github.com/learn-co-curriculum/git-remote-code-along#create-a-new-directory-and-add-a-file) come before the steps you mentioned.

Let me know if you have any additional questions!
