### ISSUE TITLE
pushing and pulling with github 

### ISSUE THREAD

**Issue by Louiefigz** [learn-co-curriculum/git-remote-code-along#6]
I was able to push the README up to github but when i was trying to pull i got an error message.  I wrote git pull in my terminal and got this message.  There may be a step that is missing. 

// ♥ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

```
git pull <remote> <branch>
```

If you wish to set tracking information for this branch you can do so with:

```
git branch --set-upstream-to=origin/<branch> master
```

**Comment by AnnJohn** [comment]
@joshuabamboo needs to be updated. thanks.

**Comment by deniznida** [comment]
added the -u to git push to track the commited branch
