### ISSUE TITLE
"git push -u" command result in "fatal: The current branch has no upstream branch" message.

### ISSUE THREAD

**Issue by beingy** [learn-co-curriculum/git-remote-code-along#9]
For "Push code to Github" section, for number heading 4, I had to use "git push -u origin master" to do this successfully.

**Comment by AnnJohn** [comment]
hi @beingy in the earlier step you should have done 'git remote add origin your-remote-repository-URL' which should have set the remote branch. If you had issues with that, please use the Ask a Question tool in Learn and someone from our team will get back to you. Thanks.
